### PR TITLE
Some scripts related with Agents and Shared Agents

### PR DESCRIPTION
**Pull request by kuisathaverat**
Scripts for :
create an script to create Agents from a Jenkins instance
disable agents on a Jenkins instance
delete agents on a Jenkins instance

@reviewbybees @cloudbees/team-support

### CODE REVIEW

**Comment by kuisathaverat** [comment]
@batmat I added other to delete Agents

**Comment by escoem** [comment]
🐝

**Comment by batmat** [comment]
:bee:

**Comment by MCardenasBlanco** [comment]
🐝

**Pull request merged**
