### PR TITLE
Builds cleaner

### PR DESCRIPTION
**Pull request by marco2704**
Groovy Scripts which deletes all builds keeping ${MAX_BUILDS} from all job of the Jenkins Instance. It checks build is not building and it also keeps the keep forever, lastStableBuild, lastSuccessfulBuild, lastSuccessfulBuild, lastUnstableBuild, lastUnsuccessfulBuild in case are not included in the ${MAX_BUILDS}.

It may be useful for large Jenkins instances where teams does not configure the "discard old build" option at their jobs.

Regards!

### CODE REVIEW

**Comment by alexanderrtaylor** [comment]
This seems dangerous and I would rather use the build discarder property instead of deleting the build. Is there a reason you do this instead? was the discarder not enough?

**Comment by marco2704** [comment]
In fact this is pretty similar to the **CleanBuildHistory.groovy**, the main difference is this does it in a global way. Sometimes having a large Jenkins setup, with multiples teams makes hard to educate users to set this property, since the Discard property is a job level configuration.

Even it takes care of the keep forever, lastStableBuild, lastSuccessfulBuild, lastSuccessfulBuild, lastUnstableBuild, lastUnsuccessfulBuild in case are not included in the keeping builds.

Regards!

**Comment by mschuijer** [comment]
Personally I use https://wiki.jenkins.io/display/JENKINS/Configuration+Slicing+Plugin for that sort of thing on our large instances. You can use that to set a value in either of those categories and job owners can see I did an update and when. We use it for several mass config changes, but it does require you to install yet another plugin. Maybe this can benefit you and others?

**Comment by alexanderrtaylor** [comment]
Yeah @mschuijer has a great idea. The script we use does it globally and you can adjust it to overwrite if the build discarding is already there.

I am just very nervous about a groovy script deleting builds and other non-experienced users running the scripts without understanding the impacts

**Comment by marco2704** [comment]
@mschuijer thanks for letting me know that option! We are going to evaluate since it seems that we can replace this script by that plugin.

@alexanderrtaylor I  completely understand your point, anyway thank you both for your time! 😄

**Pull request closed without merging**
