### PR TITLE
Add a Security script which outputs RBAC configuration

### PR DESCRIPTION
**Pull request by jpbriend**
Security script which outputs RBAC configuration on a CJOC and all its connected Masters

### CODE REVIEW

**Comment by jpbriend** [comment]
@reviewbybees

**Comment by kmadel** [comment]
@jpbriend If there is a connected master with security disabled, results in stack trace:

org.acegisecurity.userdetails.UsernameNotFoundException: kmadel
	at hudson.security.SecurityRealm$None$2.loadUserByUsername(SecurityRealm.java:495)
	at jenkins.security.ImpersonatingUserDetailsService.loadUserByUsername(ImpersonatingUserDetailsService.java:32)
	at hudson.model.User.impersonate(User.java:309)
	at com.cloudbees.opscenter.context.remote.RemoteAuthentication.toAuthentication(RemoteAuthentication.java:227)
	at com.cloudbees.opscenter.context.remote.RemoteAuthentication.impersonate(RemoteAuthentication.java:47)
	at com.cloudbees.opscenter.server.clusterops.AuthenticatedOperationsCenterToClientMasterCallable.call(AuthenticatedOperationsCenterToClientMasterCallable.java:28)

Run in http://cjoc.jenkins-latest.beedemo.net/script to see complete stacktrace.

**Comment by jpbriend** [comment]
@kmadel I added a try-catch to handle RemoteException from Masters and SecurityException if security has been disable on a Master

**Comment by batmat** [comment]
Isn't this a duplicate of https://github.com/cloudbees/jenkins-scripts/blob/master/rbac-report.groovy ?

**Pull request merged**
