### PR TITLE
Relaunch TcpAgentListener thread

### PR DESCRIPTION
**Pull request by MCardenasBlanco**
Useful for certain use cases.

### CODE REVIEW

**Comment by MCardenasBlanco** [comment]
@rkivisto , @Dohbedoh tagging you here in case you have some recommendations/objections.

**Comment by rkivisto** [comment]
[JENKINS-70334](https://issues.jenkins.io/browse/JENKINS-70334) was fixed in Jenkins 2.388 and CloudBees CI 2.387.1.2, and that was the main reason when I'd see this script being useful:
https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/diagnosing-if-the-tcp-agent-listener-port-thread-has-terminated
If a similar issue were to be introduced in a future version, this script may be useful.
For currently supported versions, I am not aware of a use case for this.

**Comment by MCardenasBlanco** [comment]
BNP has more than 1800 controllers they manage through casc. For that they are using a custom image where the init container pulls casc bundle and provisions the controller. They have found that sometimes jnlp port is still busy when Jenkins starts and that causes the tcpagenlistener to die (the fix does not help here) this script can be used as a workaround to avoid reprovisiining.

**Comment by MCardenasBlanco** [comment]
@rkivisto @Dohbedoh if you do not object, I will merge this PR so that it is available to the wider team.

**Comment by Dohbedoh** [comment]
> In s situation where you have more than 1800 controllers that you manage through casc. For that you may use a custom image where the init container pulls casc bundle and provisions the controller. You can see that sometimes jnlp port is still busy when Jenkins starts and that causes the tcpagentlistener thread to die (the fix does not help here) this script can be used as a workaround to avoid reprovisining.

I am curious about this.. Was this reported ?

**Review by Dohbedoh — APPROVED** [review]

**Pull request merged**
