### PR TITLE
JENKINS-31155 obsoletes this hack

### PR DESCRIPTION
**Pull request by jglick**
Use https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/10.

@reviewbybees esp. @kmadel

### CODE REVIEW

**Comment by kmadel** [comment]
I suppose it should be deprecated for some time, rather than pushing users of this script to update to jenkinsci/workflow-cps-global-lib-plugin#10 before they are ready - perhaps add some comments to the script that points to the changes/documentation for the new enhanced global library features.

**Comment by jglick** [comment]
I would presume that anyone who needed this workaround would have just copied the script and would not be looking at changes.

**Comment by stephenc** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

(but who is the maintainer?)

**Pull request merged**
